version: 2.1
orbs:
  docker: circleci/docker@2.4.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ryanpaul01/test1
          auth:
            username: $DOCKER_LOGIN
            password: $DOCKER_PASSWORD
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ryanpaul01/test1
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  commit:
    jobs:
      - build-and-push