version: 2.1

jobs:
  build:
    docker:
      - image: nginx
    steps:
      - checkout
      - run: cp -R ./html/* /usr/share/nginx/html
      - run: service nginx restart
      - run: curl localhost
      - run: ls /usr/share/nginx/html
      
workflows:
  build-workflow:
    jobs:
      - build
      