version: 2.1

jobs:
  build:
    docker:
      - image: nginx
    steps:
      - checkout
      - run: ls -a
      - run: apt update
      - run: apt install -y curl
      - run: curl 127.0.0.1
      
workflows:
  build-workflow:
    jobs:
      - build
      