version: 2.1

jobs:
  build:
    docker:
      - image: nginx
    steps:
      - checkout
      - run: ls -a
      - run: service nginx status
      
workflows:
  build-workflow:
    jobs:
      - build
      