version: 2.1

jobs:
  build:
    docker:
      - image: nginx
    steps:
      - checkout
      - run: ls -a
      - run: whereis nginx
      - run: curl http://127.0.0.1
      
workflows:
  build-workflow:
    jobs:
      - build
      